/**
 * RlmEmitter — typed EventEmitter wrapper for RLM lifecycle events.
 *
 * Replaces RlmToolBridge mutation methods. The engine and bridges emit typed
 * events instead of calling bridge.addSubcall/updateSubcall/etc. Listeners
 * (RlmEventAggregator, TelemetrySink) subscribe to build derived state.
 *
 * Node.js EventEmitter is synchronous — listeners run in registration order
 * during emit. No backpressure needed: engine events are sequential, one at
 * a time during the turn loop.
 */

import { EventEmitter } from "node:events";
import type { TelemetrySink } from "../telemetry/sink.ts";
import type { SubcallKind, SubcallStatus, RlmRunStatus } from "./rlm-details.ts";
import type { ProposedEdit } from "../sandbox/protocol.ts";

// ── Event payloads ──

/** Emitted when a sub-call is created. ID is auto-generated by the emitter. */
export interface SubcallCreatedEvent {
  readonly id: string;
  readonly parentId?: string;
  readonly kind: SubcallKind;
  readonly label: string;
  readonly model?: string;
  readonly detail?: string;
  readonly args?: string;
  /** Recursion depth. Required — all 9 call sites pass this. */
  readonly depth: number;
}

/** Emitted when a sub-call is updated. All fields are partial — only supplied fields are applied. */
export interface SubcallUpdatedEvent {
  readonly id: string;
  readonly status?: SubcallStatus;
  readonly detail?: string;
  readonly args?: string;
  readonly resultPreview?: string;
  /** Delta — additive on both the subcall and running totals. */
  readonly costUsd?: number;
  /** Delta — additive on both the subcall and running totals. */
  readonly tokens?: number;
}

export interface TurnEvent {
  readonly current: number;
  readonly max: number;
}

export interface RootUsageEvent {
  readonly costUsd: number;
  readonly tokens: number;
}

export interface AnswerEvent {
  readonly text: string;
}

export interface EditsEvent {
  readonly edits: ProposedEdit[];
}

export interface StatusEvent {
  readonly status: RlmRunStatus;
}

export interface RootPromptEvent {
  readonly text: string;
}

// ── RlmEmitter ──

/**
 * Typed wrapper around a Node.js EventEmitter for RLM lifecycle events.
 *
 * Auto-generates monotonic subcall IDs (`s1`, `s2`, …) via `emitSubcallCreated()`.
 * Provides typed `on*` methods that return unsubscribe functions.
 * `attachSink()` wires all events to a TelemetrySink and returns a detach function.
 */
export class RlmEmitter {
  private readonly ee = new EventEmitter();
  private seq = 0;

  // ── Emit ──

  /** Create a new sub-call entry. Returns the auto-generated ID. */
  emitSubcallCreated(init: Omit<SubcallCreatedEvent, "id">): string {
    const id = `s${++this.seq}`;
    const event: SubcallCreatedEvent = { id, ...init };
    this.ee.emit("subcall:created", event);
    return id;
  }

  /** Update an existing sub-call. All fields are partial. costUsd/tokens are additive. */
  emitSubcallUpdated(event: SubcallUpdatedEvent): void {
    this.ee.emit("subcall:updated", event);
  }

  /** Set turn progress (root-only). */
  emitTurn(current: number, max: number): void {
    this.ee.emit("turn", { current, max } satisfies TurnEvent);
  }

  /** Accumulate usage directly to root-level totals. */
  emitRootUsage(costUsd: number, tokens: number): void {
    this.ee.emit("root-usage", { costUsd, tokens } satisfies RootUsageEvent);
  }

  /** Set the final answer text (root-only). */
  emitAnswer(text: string): void {
    this.ee.emit("answer", { text } satisfies AnswerEvent);
  }

  /** Set proposed edits (root-only). */
  emitEdits(edits: ProposedEdit[]): void {
    this.ee.emit("edits", { edits } satisfies EditsEvent);
  }

  /** Set the root run status (done/error/aborted). */
  emitStatus(status: RlmRunStatus): void {
    this.ee.emit("status", { status } satisfies StatusEvent);
  }

  /** Set the root prompt text. Called once before the engine starts. */
  emitRootPrompt(text: string): void {
    this.ee.emit("root-prompt", { text } satisfies RootPromptEvent);
  }

  // ── Subscribe (returns unsubscribe function) ──

  onSubcallCreated(handler: (event: SubcallCreatedEvent) => void): () => void {
    this.ee.on("subcall:created", handler);
    return () => { this.ee.off("subcall:created", handler); };
  }

  onSubcallUpdated(handler: (event: SubcallUpdatedEvent) => void): () => void {
    this.ee.on("subcall:updated", handler);
    return () => { this.ee.off("subcall:updated", handler); };
  }

  onTurn(handler: (event: TurnEvent) => void): () => void {
    this.ee.on("turn", handler);
    return () => { this.ee.off("turn", handler); };
  }

  onRootUsage(handler: (event: RootUsageEvent) => void): () => void {
    this.ee.on("root-usage", handler);
    return () => { this.ee.off("root-usage", handler); };
  }

  onAnswer(handler: (event: AnswerEvent) => void): () => void {
    this.ee.on("answer", handler);
    return () => { this.ee.off("answer", handler); };
  }

  onEdits(handler: (event: EditsEvent) => void): () => void {
    this.ee.on("edits", handler);
    return () => { this.ee.off("edits", handler); };
  }

  onStatus(handler: (event: StatusEvent) => void): () => void {
    this.ee.on("status", handler);
    return () => { this.ee.off("status", handler); };
  }

  onRootPrompt(handler: (event: RootPromptEvent) => void): () => void {
    this.ee.on("root-prompt", handler);
    return () => { this.ee.off("root-prompt", handler); };
  }

  // ── Sink integration ──

  /**
   * Wire all lifecycle events to a TelemetrySink.
   * Returns a detach function that unsubscribes all sink listeners.
   * The caller is responsible for calling `sink.shutdown()` after detaching.
   */
  attachSink(sink: TelemetrySink): () => void {
    const unsubs: (() => void)[] = [];

    unsubs.push(this.onSubcallCreated((event) => {
      sink.start(event.id, {
        kind: event.kind,
        depth: event.depth,
        parentId: event.parentId,
        model: event.model,
        label: event.label,
        detail: event.detail,
        args: event.args,
      });
    }));

    unsubs.push(this.onSubcallUpdated((event) => {
      if (event.costUsd !== undefined || event.tokens !== undefined) {
        sink.usage(event.id, event.costUsd ?? 0, event.tokens ?? 0);
      }
      if (event.status !== undefined && event.status !== "running") {
        sink.end(event.id, {
          error: event.status === "error" ? (event.detail ?? "error") : undefined,
          resultPreview: event.resultPreview,
        });
      }
    }));

    return () => { unsubs.forEach((fn) => fn()); };
  }

  // ── Lifecycle ──

  /** Remove all listeners. Call after the run completes to prevent leaks. */
  shutdown(): void {
    this.ee.removeAllListeners();
  }
}
